# Build stage
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ ./cmd/
COPY internal/ ./internal/
COPY web/ ./web/
# RUN ls -laR /app  # list files
RUN CGO_ENABLED=0 GOOS=linux go build -o lorem-video ./cmd/server/

# Runtime stage
FROM alpine:latest
RUN apk --no-cache add ffmpeg ca-certificates
WORKDIR /app
COPY --from=builder /app/lorem-video .
COPY web/ ./web/

# Copy pregenerated data to a staging folder
COPY data/sourceVideo/ /pregen-data/sourceVideo/
COPY data/video/ /pregen-data/video/
COPY data/stream/ /pregen-data/stream/

# Setup entrypoint script
COPY entrypoint-pregen.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["./lorem-video"]
